# TINVOICES
TINVOICES_SELECT_LAST_NUMBER = SELECT MAX(number) FROM TInvoices
TINVOICES_INSERT = INSERT INTO TInvoices (id, number, date, vat, amount, \
				   state, version, createdat, updatedat, entityState) \
				   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TINVOICES_UPDATE = TInvoices SET number = ?, date = ?, vat = ?, amount = ?, \
				   state = ?, version = ?, created_at = ?, updated_at = ?, \
				   entity_state = ? WHERE id = ?
TINVOICES_DELETE = DELETE FROM TInvoices WHERE id = ?
TINVOICES_FIND_BY_ID = SELECT * FROM TInvoices WHERE id = ?
TINVOICES_FIND_BY_NIF = "SELECT i.* FROM TInvoices i \
						JOIN TWorkOrders w ON w.invoice_id = i.id \
						JOIN TVehicles v ON v.id = w.vehicle_id \
						JOIN TClients cl ON cl.id = v.client_id \
						WHERE cl.dni = ?
TINVOICES_FIND_ALL = SELECT * FROM TInvoices

# TMECHANICS
TMECHANICS_ADD = insert into TMechanics(id, nif, name, surname, version, \
				 createdAt, updatedAt, entityState) \
                 values (?, ?, ?, ?, ?, ?, ?, ?)
TMECHANICS_DELETE = delete from TMechanics where id = ?
TMECHANICS_FINDBYID = select * from TMechanics where id = ?
TMECHANICS_FINDBYNIF = select * from TMechanics where nif = ?
TMECHANICS_FINDALL = select * from TMechanics
TMECHANICS_UPDATE = update TMechanics \
                    set name = ?, surname = ?, version = version+1, \
                    updatedat = ? where id = ?

# TWORKORDERS
TWORKORDERS_FIND_NOT_INVOICED = SELECT a.id, a.version, a.vehicle_id, \
								a.description, a.date, a.state, a.amount, \
								a.mechanic_id, a.invoice_id FROM TWorkOrders AS a \
								JOIN TVehicles AS v ON a.vehicle_id = v.id JOIN \
								TClients AS c ON v.client_id = c.id WHERE a.state \
								= 'FINISHED' AND c.nif = ? AND a.invoice_id IS NULL
TWORKORDERS_FIND_BY_ID = SELECT * FROM TWorkOrders WHERE id = ?
TWORKORDERS_FIND_STATUS_BY_ID = SELECT state FROM TWorkOrders WHERE id = ?
TWORKORDERS_FIND_AMOUNT_BY_ID = SELECT amount FROM TWorkOrders WHERE id = ?
TWORKORDERS_UPDATE = UPDATE TWorkOrders SET state = ?, invoice_id = ?, version = ?, \
					 updatedAt = ?, entityState = ? WHERE id = ?
TWORKORDERS_FINDBYMECHANIC = SELECT * FROM TWORKORDERS WHERE MECHANIC_ID = ?
TWORKORDERS_INSERT = INSERT INTO TWorkOrders(id, amount, createdAt, date, description, entityState, state, updatedAt, version, invoice_id, mechanic_id, vehicle_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TWORKORDERS_FIND_BY_INTERVENTION_MECHANIC_ID = SELECT w.id, w.amount, w.createdat, w.date, w.description, w.entitystate, w.state, w.updatedat, w.version, w.invoice_id, i.mechanic_id AS mechanicId, w.vehicle_id FROM TWorkOrders w JOIN TInterventions i ON i.workorder_id = w.id WHERE i.mechanic_id = ?


# TINTERVENTIONS
TINTERVENTIONS_FINDBYMECHANIC = SELECT * FROM TInterventions WHERE mechanic_id = ?

# TCONTRACTS
TCONTRACTS_FINDBYMECHANIC = SELECT c.ID AS id, c.VERSION AS version, m.ID AS mechanicId, m.NIF AS nif, m.NAME AS mechanicName, m.SURNAME AS mechanicSurname, ct.NAME AS contractTypeName, pg.NAME AS professionalGroupName, pg.ID AS professionalGroupId, c.STARTDATE AS startDate, c.ENDDATE AS endDate, c.ANNUALBASESALARY AS annualBaseWage, c.SETTLEMENT AS settlement, c.STATE AS state FROM TCONTRACTS c LEFT JOIN TMECHANICS m ON c.MECHANIC_ID = m.ID LEFT JOIN TCONTRACTTYPES ct ON c.CONTRACTTYPE_ID = ct.ID LEFT JOIN TPROFESSIONALGROUPS pg ON c.PROFESSIONALGROUP_ID = pg.ID WHERE c.MECHANIC_ID = ?

TCONTRACTS_FINDINFORCE = SELECT c.id, c.version, m.id AS mechanicId, m.NIF AS nif, \
                         m.name AS mechanicName, m.surname AS mechanicSurname, \
                         ct.name AS contractTypeName, pg.name AS professionalGroupName, \
                         pg.id AS professionalGroupId, \
                         c.startDate, c.endDate, c.annualBaseSalary AS annualBaseWage, \
                         c.settlement, c.state \
                         FROM TCONTRACTS c \
                         JOIN TMECHANICS m ON c.mechanic_id = m.id \
                         JOIN TCONTRACTTYPES ct ON c.contractType_id = ct.id \
                         JOIN TPROFESSIONALGROUPS pg ON c.professionalGroup_id = pg.id \
                         WHERE c.state = 'IN_FORCE'

#TCONTRACTS_FINDINFORCEORENDINGTHISMONTH = SELECT c.ID AS id, c.VERSION AS version, c.STARTDATE AS startDate, c.ENDDATE AS endDate, c.STATE AS state, c.ANNUALBASESALARY AS annualBaseSalary, c.SETTLEMENT AS settlement, c.MECHANIC_ID AS mechanicId, m.NIF AS nif, m.NAME AS mechanicName, m.SURNAME AS mechanicSurname, ct.NAME AS contractTypeName, pg.NAME AS professionalGroupName, pg.ID AS professionalGroupId FROM TCONTRACTS c JOIN TMECHANICS m ON c.MECHANIC_ID = m.ID JOIN TCONTRACTTYPES ct ON c.CONTRACTTYPE_ID = ct.ID JOIN TPROFESSIONALGROUPS pg ON c.PROFESSIONALGROUP_ID = pg.ID WHERE (c.STATE = 'IN_FORCE' AND c.STARTDATE <= ? AND (c.ENDDATE IS NULL OR c.ENDDATE >= ?)) OR (c.STATE = 'TERMINATED' AND MONTH(c.ENDDATE) = ? AND YEAR(c.ENDDATE) = ?)
TCONTRACTS_FINDINFORCEORENDINGTHISMONTH = SELECT c.ID AS id, c.VERSION AS version, c.STARTDATE AS startDate, c.ENDDATE AS endDate, c.STATE AS state, c.ANNUALBASESALARY AS annualBaseSalary, c.SETTLEMENT AS settlement, c.MECHANIC_ID AS mechanicId, m.NIF AS nif, m.NAME AS mechanicName, m.SURNAME AS mechanicSurname, ct.NAME AS contractTypeName, pg.NAME AS professionalGroupName, pg.ID AS professionalGroupId FROM TCONTRACTS c JOIN TMECHANICS m ON c.MECHANIC_ID = m.ID JOIN TCONTRACTTYPES ct ON c.CONTRACTTYPE_ID = ct.ID JOIN TPROFESSIONALGROUPS pg ON c.PROFESSIONALGROUP_ID = pg.ID WHERE c.STATE = 'IN_FORCE' OR (c.STATE = 'TERMINATED' AND MONTH(c.ENDDATE) = ? AND YEAR(c.ENDDATE) = ?)
TCONTRACTS_FINDBYPROFESSIONALGROUP = SELECT c.ID AS id, c.VERSION AS version, c.STARTDATE AS startDate, c.ENDDATE AS endDate, c.STATE AS state, c.ANNUALBASESALARY AS annualBaseSalary, c.SETTLEMENT AS settlement, c.MECHANIC_ID AS mechanicId, m.NIF AS nif, m.NAME AS mechanicName, m.SURNAME AS mechanicSurname, ct.NAME AS contractTypeName, pg.NAME AS professionalGroupName, pg.ID AS professionalGroupId FROM TCONTRACTS c JOIN TMECHANICS m ON c.MECHANIC_ID = m.ID JOIN TCONTRACTTYPES ct ON c.CONTRACTTYPE_ID = ct.ID JOIN TPROFESSIONALGROUPS pg ON c.PROFESSIONALGROUP_ID = pg.ID WHERE c.PROFESSIONALGROUP_ID = ?
TCONTRACTS_EXISTS_FOR_GROUP = SELECT COUNT(*) FROM TCONTRACTS WHERE PROFESSIONALGROUP_ID = ?

# TPAYROLLS
TPAYROLLS_ADD = INSERT INTO TPAYROLLS (id, version, contract_id, date, baseSalary, extraSalary, productivityEarning, trienniumEarning, taxDeduction, nicDeduction, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TPAYROLLS_DELETEBYID = DELETE FROM TPAYROLLS WHERE ID = ?
TPAYROLLS_FINDBYID = SELECT * FROM TPAYROLLS WHERE ID = ?
TPAYROLLS_FINDINDATES = SELECT id, version, contract_id, date, baseSalary, extraSalary, productivityEarning, trienniumEarning, taxDeduction, nicDeduction, CREATEDAT, UPDATEDAT FROM TPAYROLLS WHERE MONTH(date) = ? AND YEAR(date) = ? 
TPAYROLLS_FINDBYCONTRACTIDSINDATES=select * from TPayrolls where contract_id = ? and month(date) = ? and year(date) = ?
TPAYROLLS_FINDBYCONTRACTIDS=select * from TPayrolls where contract_id = ?
TPAYROLLS_FINDALL = SELECT * FROM TPAYROLLS
TPAYROLLS_FINDBYMECHANIC = SELECT p.ID AS id, p.VERSION AS version, p.DATE AS date, (p.BASESALARY + p.EXTRASALARY + p.PRODUCTIVITYEARNING + p.TRIENNIUMEARNING - p.TAXDEDUCTION - p.NICDEDUCTION) AS netSalary FROM TPAYROLLS p JOIN TCONTRACTS c ON p.CONTRACT_ID = c.ID WHERE c.MECHANIC_ID = ?


# TPROFESSIONALGROUP
TPROFESSIONALGROUPS_ADD = INSERT INTO TPROFESSIONALGROUPS (id, createdAt, entityState, name, productivityRate, trienniumPayment, updatedAt, version) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
TPROFESSIONALGROUPS_DELETE = DELETE FROM TPROFESSIONALGROUPS WHERE id = ?
TPROFESSIONALGROUPS_UPDATE = UPDATE TPROFESSIONALGROUPS SET trienniumPayment = ?, productivityRate = ?, updatedAt = ?, version = ? where id = ?
TPROFESSIONALGROUPS_FINDBYID = SELECT * FROM TPROFESSIONALGROUPS WHERE ID = ?
TPROFESSIONALGROUPS_FINDBYNAME = SELECT * FROM TPROFESSIONALGROUPS WHERE name = ?
TPROFESSIONALGROUPS_FINDALL = SELECT * FROM TPROFESSIONALGROUPS