# TINVOICES
TINVOICES_SELECT_LAST_NUMBER = SELECT MAX(number) FROM TInvoices
TINVOICES_INSERT = INSERT INTO TInvoices \
                   (id, number, date, vat, amount, state, version, \
                   createdat, updatedat, entityState) \
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)



# TMECHANICS
TMECHANICS_ADD = insert into TMechanics(id, nif, name, surname, version, \
                 createdat, updatedat, entityState) \
                 values (?, ?, ?, ?, ?, ?, ?, ?)
TMECHANICS_DELETE = delete from TMechanics where id = ?
TMECHANICS_FIND_BY_NIF = select id, nif, name, surname, version, createdat, \
                       updatedat, entitystate from TMechanics \
                       where nif = ?
TMECHANICS_FIND_ALL = select id, nif, name, surname, version, createdat, \
                     updatedat, entitystate from TMechanics
TMECHANICS_UPDATE = update TMechanics \
                    set name = ?, surname = ?, version = version+1, \
                    updatedat = ? where id = ?
TMECHANICS_FIND_BY_ID = select id, nif, name, surname, version, createdat, \
                      updatedat, entitystate from TMechanics \
                      where id = ?
# TWORKORDERS
TWORKORDERS_FIND_ALL = SELECT * FROM TWORKORDERS

TWORKORDERS_UPDATE = update TWorkOrders \
                     set invoice_id = ?, state = ?, version = version + 1, \
                     updatedat = ? \
                     WHERE id = ?
                     
TWORKORDERS_FIND_NOT_INVOICED = select a.id, a.createdat, a.description, \
                                a.date, a.state, a.amount \
                                from TWorkOrders as a, TVehicles as v, \
                                TClients as c \
                                where a.vehicle_id = v.id \
                                  and v.client_id = c.id \
                                  and a.state = 'FINISHED' \
                                  and c.nif = ?
                                  
TWORKORDERS_UPDATE_VERSION = update TWorkOrders \
                             set version=version+1 where id = ?
                             
TWORKORDERS_FIND_ID_BY_ID = SELECT id, amount, createdat, date, description, \
                            entitystate, state, updatedat, version, \
                            invoice_id, mechanic_id, vehicle_id \
                            FROM TWorkOrders where id = ?
                            
TWORKORDERS_FIND_STATUS_BY_ID = SELECT state FROM TWorkOrders WHERE id = ?

TWORKORDERS_FIND_AMOUNT_BY_ID = SELECT amount FROM TWorkOrders WHERE id = ?

TWORKORDERS_UPDATE_INVOICEID = UPDATE TWorkOrders \
                               SET invoice_id = ? WHERE id = ?
                               
TWORKORDERS_UPDATE_STATE = UPDATE TWorkOrders \
                           SET state = 'INVOICED' WHERE id = ?
                           
TWORKORDERS_UPDATE_TIMESTAMP = UPDATE TWorkOrders \
                               SET updatedat = ? WHERE id = ?
                               
TWORKORDERS_FIND_BY_MECHANICID = select w.id, w.amount, w.createdat, w.date, \
								w.description, w.entitystate, w.state, \
								w.updatedat, w.version, w.invoice_id, \
								w.mechanic_id, w.vehicle_id  from TWorkOrders \
								 w where w.mechanic_id = ?

TWORKORDERS_FIND_BY_INTERVENTION_M_ID = SELECT w.id, w.amount, \
								w.createdat, w.date, w.description, \
								w.entitystate, w.state, w.updatedat, \
								w.version, w.invoice_id, w.mechanic_id, \
								w.vehicle_id FROM TWorkOrders w JOIN \
								TInterventions i ON i.workorder_id = w.id \
								WHERE i.mechanic_id = ?



# TINTERVENTIONS
TINTERVENTIONS_FIND_BY_MECHANICID = SELECT id, createdat, date, entityState, \
                                  minutes, updatedat, version, mechanic_id, \
                                  workorder_id \
                                  FROM TInterventions WHERE mechanic_id = ?
# TPAYROLLS
TPAYROLLS_INSERT = INSERT INTO TPAYROLLS (id, basesalary, extrasalary, \
				  trienniumearning, productivityearning, taxdeduction, \
				  nicdeduction, date, contract_id, version, createdat, \
				  updatedat, entitystate) VALUES (?, ?, ?, ?, ?, \
				  ?, ?, ?, ?, ?, ?, ?, ?)

TPAYROLLS_FIND_BY_ID = SELECT id, basesalary, createdat, date, entitystate, \
					extrasalary, nicdeduction, productivityearning, \
					taxdeduction, trienniumearning, updatedat, version, \
					contract_id from TPAYROLLS WHERE id = ?
TPAYROLLS_FIND_ALL = SELECT id, basesalary, createdat, date, entitystate, \
					extrasalary, nicdeduction, productivityearning, \
					taxdeduction, trienniumearning, updatedat, version, \
					contract_id from TPAYROLLS
					
TPAYROLLS_FIND_ALL_FOR_MECHANIC = SELECT p.id, p.basesalary, p.createdat, \
  								  p.date, p.entitystate, p.extrasalary, \
  								  p.nicdeduction, p.productivityearning, \
  								  p.taxdeduction, p.trienniumearning, \
  								  p.updatedat, p.version, p.contract_id \
  								  FROM TPAYROLLS AS p JOIN TCONTRACTS AS c \
  								  ON p.contract_id = c.id WHERE \
  								  c.mechanic_id = ?
TPAYROLLS_FIND_LAST_MONTH = SELECT id, basesalary, createdat, date, \
					entitystate, extrasalary, nicdeduction, \
					productivityearning, taxdeduction, trienniumearning, \
					updatedat, version, contract_id from TPAYROLLS WHERE \
					date >= ? AND date < ?
TPAYROLLS_DELETE = DELETE from TPayrolls WHERE id = ?

TPAYROLLS_LAST_MONTH_MECHANIC = SELECT p.id, p.basesalary, p.createdat, \
									 date, p.entitystate, p.extrasalary, \
									 p.nicdeduction, p.productivityearning, \
       								 p.taxdeduction, p.trienniumearning, \
       								 p.updatedat, p.version, p.contract_id \
       								FROM TPAYROLLS AS p JOIN TCONTRACTS AS c \
       								 ON p.contract_id = c.id WHERE \
       								 c.mechanic_id = ? AND p.date >= ? AND \
       								 p.date < ?
TPAYROLLS_FIND_BY_PROFESSIONALGROUPS = SELECT p.id, p.basesalary, p.createdat, \
									 date, p.entitystate, p.extrasalary, \
									 p.nicdeduction, p.productivityearning, \
       								 p.taxdeduction, p.trienniumearning, \
       								 p.updatedat, p.version, p.contract_id \
       								FROM TPAYROLLS AS p JOIN TCONTRACTS AS c \
       								 ON p.contract_id = c.id JOIN \
       								 TProfessionalGroups pg ON \
       								 c.professionalgroup_id = pg.id WHERE \
       								 pg.name = ?
       								 
TPAYROLLS_FIND_CONTRACT_BETWEEN = SELECT p.id, p.basesalary, p.createdat, \
									 date, p.entitystate, p.extrasalary, \
									 p.nicdeduction, p.productivityearning, \
       								 p.taxdeduction, p.trienniumearning, \
       								 p.updatedat, p.version, p.contract_id \
       								FROM TPAYROLLS AS p WHERE p.contract_id \
       								= ? and p.date >= ? AND p.date < ?

       	
# TPROFESSIONALGROUPS
TPROFESSIONALGROUPS_FIND_BY_NAME = SELECT id,createdat,entitystate, name, \
								   productivityrate, trienniumpayment , \
								   updatedat,version from TPROFESSIONALGROUPS \
								   WHERE name = ?
TPROFESSIONALGROUPS_FIND_BY_ID = SELECT id,createdat,entitystate, name, \
								   productivityrate, trienniumpayment , \
								   updatedat,version from TPROFESSIONALGROUPS \
								   WHERE id = ?
# TCONTRACTS
TCONTRACTS_FIND_BY_ID = SELECT c.id, c.mechanic_id, c.startdate,\
 								   c.enddate, c.annualbasesalary, c.taxrate, \
 								   c.contracttype_id,c.professionalgroup_id, \
 								   c.settlement, c.version, c.entitystate, \
 								   c.createdat, c.updatedat, c.state FROM \
 								   TCONTRACTS c WHERE c.id = ?


TCONTRACTS_FIND_ACTIVE_AT = SELECT c.id, c.startdate, \
							c.mechanic_id, c.professionalgroup_id, c.state, \
							c.enddate, c.annualbasesalary, c.version, \
							c.entitystate, c.createdat, c.updatedat, \
							c.contracttype_id, c.taxrate, c.settlement FROM \
							TCONTRACTS AS c WHERE c.startdate <= ? AND \
							(c.enddate IS NULL OR c.enddate > ? OR c.state=\
							'IN_FORCE')
							
TCONTRACTS_FIND_TERMINATED_BETWEEN = SELECT c.id, c.mechanic_id, c.startdate,\
 								   c.enddate, c.annualbasesalary, c.taxrate, \
 								   c.contracttype_id,c.professionalgroup_id, \
 								   c.settlement, c.version, c.entitystate, \
 								   c.createdat, c.updatedat, c.state FROM \
 								   TCONTRACTS c WHERE c.enddate IS NOT NULL \
 								   AND c.enddate 	>= ? AND c.enddate <= ?														   						 
TCONTRACTS_FIND_BY_CONTRACTTYPE = SELECT c.id, c.mechanic_id, c.startdate,\
 								   c.enddate, c.annualbasesalary, c.taxrate, \
 								   c.contracttype_id,c.professionalgroup_id, \
 								   c.settlement, c.version, c.entitystate, \
 								   c.createdat, c.updatedat, c.state FROM \
 								   TCONTRACTS c WHERE c.contracttype_id = ?
TCONTRACTS_FIND_CONTRACTED_MECHANIC = SELECT c.id, c.mechanic_id, c.startdate,\
 								   c.enddate, c.annualbasesalary, c.taxrate, \
 								   c.contracttype_id,c.professionalgroup_id, \
 								   c.settlement, c.version, c.entitystate, \
 								   c.createdat, c.updatedat, c.state FROM \
 								   TCONTRACTS c WHERE c.mechanic_id =?
 								   
 TCONTRACTS_FIND_CONTRACTED_MECHANICS = SELECT c.id, c.mechanic_id, c.startdate,\
 								   c.enddate, c.annualbasesalary, c.taxrate, \
 								   c.contracttype_id,c.professionalgroup_id, \
 								   c.settlement, c.version, c.entitystate, \
 								   c.createdat, c.updatedat, c.state FROM \
 								   TCONTRACTS c WHERE c.state = 'IN_FORCE' 															   						   
 								   
 # TCONTRACTSTYPE
TCONTRACTSTYPE_INSERT = INSERT INTO TCONTRACTTYPES(id, version, createdat, \
						updatedat, entitystate, compensationdaysperyear, name) \
						VALUES ( ?, ?, ?, ?, ?, ?, ?)
						
TCONTRACTSTYPE_UPDATE = UPDATE TCONTRACTTYPES set compensationdaysperyear=?, \
						entitystate=?,version=?,updatedat =? where id = ? 						
						
TCONTRACTSTYPE_DELETE = DELETE FROM TCONTRACTTYPES WHERE name = ?

TCONTRACTSTYPE_FIND_BY_ID = SELECT id,version,createdat,updatedat, \
							entitystate, compensationdaysperyear, name \
							FROM TCONTRACTTYPES WHERE id = ?
TCONTRACTSTYPE_FIND_BY_NAME = SELECT id,version,createdat,updatedat, \
							entitystate, compensationdaysperyear, name \
							FROM TCONTRACTTYPES WHERE name = ?
							
TCONTRACTSTYPE_FIND_ALL =SELECT id,version,createdat,updatedat, \
						 entitystate, compensationdaysperyear, name \
						 FROM TCONTRACTSTYPES